apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/n4mlz/kubernetes-test.git
    path: apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
