apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: etcd
    targetRevision: 10.1.4
  destination:
    server: https://kubernetes.default.svc
    namespace: etcd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
