apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 59.1.0
    chart: kube-prometheus-stack
destination:
  server: https://kubernetes.default.svc
  namespace: prometheus

