alertmanager:
  ingress:
    enabled: true
    hosts:
      - kubernates-test
    paths:
      - /alertmanager
grafana:
  ingress:
    enabled: true
    hosts:
      - kubernates-test
    paths:
      - /grafana
prometheus:
  ingress:
    enabled: true
    hosts:
      - kubernates-test
    paths:
      - /prometheus
