alertmanager:
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls:
      - hosts:
        - alartmanager
grafana:
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls:
      - hosts:
        - grafana
prometheus:
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls:
      - hosts:
        - prometheus
