apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport-service
  namespace: argocd
spec:
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort

