apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-test
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx-test.n4mlz.dev`)
      kind: Rule
      services:
        - name: nginx-test-service
          port: 80

