apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-custom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/n4mlz/kubernetes-test.git'
    path: argocd-custom
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
